#!/usr/bin/env node

require("./scripts/cli/main")
  .main(process.argv.slice(2), {
    rootDir: __dirname,
    profile: "cn",
    programName: "sclaw_cn",
  })
  .then(
    (code) => {
      process.exitCode = code;
    },
    (error) => {
      process.stderr.write(`${error.message}\n`);
      process.exitCode = 1;
    },
  );
