from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List

from converters.base import FormatConverter
from schemas.structure_model_v1 import StructureModelV1


@dataclass
class _ParseState:
    nodes: List[Dict[str, Any]]
    elements: List[Dict[str, Any]]
    materials: List[Dict[str, Any]]
    sections: List[Dict[str, Any]]
    load_cases_map: Dict[str, Dict[str, Any]]
    load_combinations: List[Dict[str, Any]]


class MidasTextV1Converter(FormatConverter):
    """
    Minimal MIDAS-like text format converter.

    Supported records:
      NODE,id,x,y,z
      REST,node,ux,uy,uz,rx,ry,rz (0/1)
      MAT,id,name,E,nu,rho[,fy]
      SEC,id,name,type,A,Iy,Iz[,J][,G]
      ELEM,id,type,nodeI,nodeJ,material,section
      LOADCASE,id[,type]
      NLOAD,loadCase,node,fx,fy,fz[,mx][,my][,mz]
      COMBO,id,caseA=1.2;caseB=1.4
    """

    format_name = "midas-text-1"

    def to_v1(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        text = payload.get("text")
        if not isinstance(text, str) or not text.strip():
            raise ValueError("line 1: payload.text is required for midas-text-1")

        state = _ParseState(
            nodes=[],
            elements=[],
            materials=[],
            sections=[],
            load_cases_map={},
            load_combinations=[],
        )

        node_index: Dict[str, Dict[str, Any]] = {}
        for idx, raw_line in enumerate(text.splitlines(), start=1):
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue

            fields = [part.strip() for part in line.split(",")]
            tag = fields[0].upper()
            data = fields[1:]

            if tag == "NODE":
                node = self._parse_node(idx, data)
                node_index[node["id"]] = node
                state.nodes.append(node)
                continue
            if tag == "REST":
                self._parse_rest(idx, data, node_index)
                continue
            if tag == "MAT":
                state.materials.append(self._parse_material(idx, data))
                continue
            if tag == "SEC":
                state.sections.append(self._parse_section(idx, data))
                continue
            if tag == "ELEM":
                state.elements.append(self._parse_element(idx, data))
                continue
            if tag == "LOADCASE":
                load_case = self._parse_load_case(idx, data)
                state.load_cases_map[load_case["id"]] = load_case
                continue
            if tag == "NLOAD":
                self._parse_nload(idx, data, state.load_cases_map)
                continue
            if tag == "COMBO":
                state.load_combinations.append(self._parse_combo(idx, data))
                continue

            raise ValueError(f"line {idx}: unsupported record '{tag}'")

        return {
            "schema_version": "1.0.0",
            "unit_system": payload.get("units", "SI"),
            "nodes": state.nodes,
            "elements": state.elements,
            "materials": state.materials,
            "sections": state.sections,
            "load_cases": list(state.load_cases_map.values()),
            "load_combinations": state.load_combinations,
            "metadata": {
                "source": "midas-text-1",
            },
        }

    def from_v1(self, model: StructureModelV1) -> Dict[str, Any]:
        lines: List[str] = [
            "# MIDAS-TEXT-1 generated by StructureClaw",
            "# NODE,id,x,y,z",
            "# REST,node,ux,uy,uz,rx,ry,rz",
            "# MAT,id,name,E,nu,rho,fy",
            "# SEC,id,name,type,A,Iy,Iz,J,G",
            "# ELEM,id,type,nodeI,nodeJ,material,section",
            "# LOADCASE,id,type",
            "# NLOAD,loadCase,node,fx,fy,fz,mx,my,mz",
            "# COMBO,id,case=factor;...",
        ]

        for node in model.nodes:
            lines.append(f"NODE,{node.id},{node.x},{node.y},{node.z}")
            if node.restraints is not None:
                rest = ",".join("1" if bool(v) else "0" for v in node.restraints)
                lines.append(f"REST,{node.id},{rest}")

        for material in model.materials:
            fy = "" if material.fy is None else str(material.fy)
            lines.append(
                f"MAT,{material.id},{material.name},{material.E},{material.nu},{material.rho},{fy}".rstrip(",")
            )

        for section in model.sections:
            props = section.properties or {}
            a = props.get("A", "")
            iy = props.get("Iy", props.get("Iz", ""))
            iz = props.get("Iz", props.get("Iy", ""))
            j = props.get("J", "")
            g = props.get("G", "")
            lines.append(f"SEC,{section.id},{section.name},{section.type},{a},{iy},{iz},{j},{g}".rstrip(","))

        for element in model.elements:
            n1 = element.nodes[0] if len(element.nodes) > 0 else ""
            n2 = element.nodes[1] if len(element.nodes) > 1 else ""
            lines.append(f"ELEM,{element.id},{element.type},{n1},{n2},{element.material},{element.section}")

        for load_case in model.load_cases:
            lines.append(f"LOADCASE,{load_case.id},{load_case.type}")
            for load in load_case.loads:
                node = load.get("node", "")
                fx = load.get("fx", 0.0)
                fy = load.get("fy", 0.0)
                fz = load.get("fz", 0.0)
                mx = load.get("mx", load.get("momentX", 0.0))
                my = load.get("my", load.get("momentY", 0.0))
                mz = load.get("mz", load.get("momentZ", 0.0))
                lines.append(f"NLOAD,{load_case.id},{node},{fx},{fy},{fz},{mx},{my},{mz}")

        for combo in model.load_combinations:
            pairs = ";".join(f"{case_id}={factor}" for case_id, factor in combo.factors.items())
            lines.append(f"COMBO,{combo.id},{pairs}")

        return {
            "format_version": self.format_name,
            "units": model.unit_system,
            "text": "\n".join(lines) + "\n",
        }

    def _parse_node(self, line_no: int, data: List[str]) -> Dict[str, Any]:
        if len(data) < 4:
            raise ValueError(f"line {line_no}: NODE requires id,x,y,z")
        return {
            "id": data[0],
            "x": self._to_float(line_no, "NODE.x", data[1]),
            "y": self._to_float(line_no, "NODE.y", data[2]),
            "z": self._to_float(line_no, "NODE.z", data[3]),
        }

    def _parse_rest(self, line_no: int, data: List[str], node_index: Dict[str, Dict[str, Any]]) -> None:
        if len(data) < 7:
            raise ValueError(f"line {line_no}: REST requires node,ux,uy,uz,rx,ry,rz")
        node_id = data[0]
        node = node_index.get(node_id)
        if node is None:
            raise ValueError(f"line {line_no}: REST references unknown node '{node_id}'")

        restraints: List[bool] = []
        for idx, raw in enumerate(data[1:7], start=1):
            value = raw.strip()
            if value not in {"0", "1"}:
                raise ValueError(f"line {line_no}: REST value {idx} must be 0 or 1, got '{value}'")
            restraints.append(value == "1")
        node["restraints"] = restraints

    def _parse_material(self, line_no: int, data: List[str]) -> Dict[str, Any]:
        if len(data) < 5:
            raise ValueError(f"line {line_no}: MAT requires id,name,E,nu,rho[,fy]")
        item: Dict[str, Any] = {
            "id": data[0],
            "name": data[1],
            "E": self._to_float(line_no, "MAT.E", data[2]),
            "nu": self._to_float(line_no, "MAT.nu", data[3]),
            "rho": self._to_float(line_no, "MAT.rho", data[4]),
        }
        if len(data) >= 6 and data[5] != "":
            item["fy"] = self._to_float(line_no, "MAT.fy", data[5])
        return item

    def _parse_section(self, line_no: int, data: List[str]) -> Dict[str, Any]:
        if len(data) < 4:
            raise ValueError(f"line {line_no}: SEC requires id,name,type,A[,Iy][,Iz][,J][,G]")
        props: Dict[str, Any] = {
            "A": self._to_float(line_no, "SEC.A", data[3]),
        }
        if len(data) >= 5 and data[4] != "":
            props["Iy"] = self._to_float(line_no, "SEC.Iy", data[4])
        if len(data) >= 6 and data[5] != "":
            props["Iz"] = self._to_float(line_no, "SEC.Iz", data[5])
        if len(data) >= 7 and data[6] != "":
            props["J"] = self._to_float(line_no, "SEC.J", data[6])
        if len(data) >= 8 and data[7] != "":
            props["G"] = self._to_float(line_no, "SEC.G", data[7])
        return {
            "id": data[0],
            "name": data[1],
            "type": data[2],
            "properties": props,
        }

    def _parse_element(self, line_no: int, data: List[str]) -> Dict[str, Any]:
        if len(data) < 6:
            raise ValueError(f"line {line_no}: ELEM requires id,type,nodeI,nodeJ,material,section")
        return {
            "id": data[0],
            "type": data[1] or "beam",
            "nodes": [data[2], data[3]],
            "material": data[4],
            "section": data[5],
        }

    def _parse_load_case(self, line_no: int, data: List[str]) -> Dict[str, Any]:
        if len(data) < 1:
            raise ValueError(f"line {line_no}: LOADCASE requires id[,type]")
        return {
            "id": data[0],
            "type": data[1] if len(data) > 1 and data[1] else "other",
            "loads": [],
        }

    def _parse_nload(self, line_no: int, data: List[str], load_cases: Dict[str, Dict[str, Any]]) -> None:
        if len(data) < 6:
            raise ValueError(f"line {line_no}: NLOAD requires case,node,fx,fy,fz[,mx][,my][,mz]")
        case_id = data[0]
        case = load_cases.get(case_id)
        if case is None:
            raise ValueError(f"line {line_no}: NLOAD references unknown load case '{case_id}'")

        load: Dict[str, Any] = {
            "node": data[1],
            "fx": self._to_float(line_no, "NLOAD.fx", data[2]),
            "fy": self._to_float(line_no, "NLOAD.fy", data[3]),
            "fz": self._to_float(line_no, "NLOAD.fz", data[4]),
        }
        if len(data) > 5 and data[5] != "":
            load["mx"] = self._to_float(line_no, "NLOAD.mx", data[5])
        if len(data) > 6 and data[6] != "":
            load["my"] = self._to_float(line_no, "NLOAD.my", data[6])
        if len(data) > 7 and data[7] != "":
            load["mz"] = self._to_float(line_no, "NLOAD.mz", data[7])
        case["loads"].append(load)

    def _parse_combo(self, line_no: int, data: List[str]) -> Dict[str, Any]:
        if len(data) < 2:
            raise ValueError(f"line {line_no}: COMBO requires id and factors expression")
        factors: Dict[str, float] = {}
        for raw in data[1].split(";"):
            entry = raw.strip()
            if not entry:
                continue
            if "=" not in entry:
                raise ValueError(f"line {line_no}: COMBO factor '{entry}' must be case=factor")
            case_id, raw_factor = entry.split("=", 1)
            factors[case_id.strip()] = self._to_float(line_no, f"COMBO.{case_id.strip()}", raw_factor.strip())
        return {
            "id": data[0],
            "factors": factors,
        }

    def _to_float(self, line_no: int, field: str, raw: str) -> float:
        try:
            return float(raw)
        except Exception as exc:
            raise ValueError(f"line {line_no}: invalid number for {field}: '{raw}'") from exc
